
spring:
  data:
    redis:
      #数据库索引
      database: 0
      #服务器地址
      host: 192.168.10.117
      #端口号
      port: 6379
      #redis密码（默认为空）
      password: 123456
      #连接redis超时时间
      timeout: 3000
